name: Windows Application

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install PyInstaller
      run: pip install pyinstaller
    - name: Build application
      run: pyinstaller ToDo_Application/main.spec
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-app
        path: dist/main.exe